[pytest]
testpaths = tests
markers =
    integration: mark test as requiring live external Google Earth Engine API credentials
filterwarnings =
    ignore::DeprecationWarning
    ignore::FutureWarning
