"""Land-cover change detection and transition matrix calculation engine.

Authoritative spatial comparison between two classification rasters/grids.
Computes 5x5 transition matrix, mangrove gross gain/loss, net change,
confidence proxy heuristics, and change GeoJSON features.
"""
import logging
from typing import Any, Dict, List, Optional, Sequence
import numpy as np

from .labels import (
    LAND_COVER_CLASSES,
    CLASS_NAMES,
    get_class_name,
    validate_class_id,
)

logger = logging.getLogger("sundarban.ml.change_detection")

# Centralized spatial resolution constants
CELL_SIZE_METERS: int = 20
CELL_AREA_HECTARES: float = 0.04  # (20m * 20m) / 10,000 m²/ha
DEFAULT_CONFIDENCE_THRESHOLD: float = 0.60
DEFAULT_SEASONAL_WINDOW: str = "Jan 01 - Mar 31"

# Authoritative change categories
CHANGE_CATEGORY_STABLE: str = "STABLE"
CHANGE_CATEGORY_MANGROVE_LOSS: str = "MANGROVE_LOSS"
CHANGE_CATEGORY_MANGROVE_GAIN: str = "MANGROVE_GAIN"
CHANGE_CATEGORY_CLASS_CONVERSION: str = "CLASS_CONVERSION"
CHANGE_CATEGORY_LOW_CONFIDENCE: str = "LOW_CONFIDENCE_CHANGE"


class SpatialCoverageMismatchError(ValueError):
    """Raised when spatial grids or cell counts between comparison years do not match."""
    pass


class IncompatibleModelVersionError(ValueError):
    """Raised when comparing classifications generated with incompatible model or feature versions."""
    pass


class InvalidTemporalComparisonError(ValueError):
    """Raised when baseline and comparison years violate temporal ordering rules."""
    pass


def validate_temporal_consistency(from_year: int, to_year: int) -> None:
    """Validate that comparison years satisfy temporal ordering (from_year < to_year)."""
    if from_year >= to_year:
        raise InvalidTemporalComparisonError(
            f"Invalid temporal comparison: baseline year {from_year} must be strictly less than comparison year {to_year}."
        )


def validate_model_compatibility(
    model_2020_info: Dict[str, Any],
    model_2025_info: Dict[str, Any],
    allow_mismatch: bool = False,
) -> None:
    """Ensure both land-cover classifications were generated by the same classifier version."""
    v_2020 = model_2020_info.get("modelVersion", "rf-v1")
    v_2025 = model_2025_info.get("modelVersion", "rf-v1")
    fv_2020 = model_2020_info.get("featureVersion", "sentinel2-v1")
    fv_2025 = model_2025_info.get("featureVersion", "sentinel2-v1")

    if (v_2020 != v_2025 or fv_2020 != fv_2025) and not allow_mismatch:
        raise IncompatibleModelVersionError(
            f"Incompatible model versions: Baseline uses {v_2020} ({fv_2020}) while comparison uses {v_2025} ({fv_2025})."
        )


def categorize_transition(
    from_class: int,
    to_class: int,
    confidence: float = 1.0,
    confidence_threshold: float = DEFAULT_CONFIDENCE_THRESHOLD,
) -> str:
    """Categorize land-cover transition into authoritative taxonomic categories."""
    if confidence < confidence_threshold and from_class != to_class:
        return CHANGE_CATEGORY_LOW_CONFIDENCE

    if from_class == to_class:
        return CHANGE_CATEGORY_STABLE

    # Class 0 = Mangrove
    if from_class == 0 and to_class != 0:
        return CHANGE_CATEGORY_MANGROVE_LOSS

    if from_class != 0 and to_class == 0:
        return CHANGE_CATEGORY_MANGROVE_GAIN

    return CHANGE_CATEGORY_CLASS_CONVERSION


def compute_transition_matrix(
    grid_baseline: Sequence[int],
    grid_comparison: Sequence[int],
    conf_baseline: Optional[Sequence[float]] = None,
    conf_comparison: Optional[Sequence[float]] = None,
    cell_area_ha: float = CELL_AREA_HECTARES,
    confidence_threshold: float = DEFAULT_CONFIDENCE_THRESHOLD,
) -> Dict[str, Any]:
    """Perform cell-by-cell spatial comparison and compute complete 5x5 transition matrix.

    Args:
        grid_baseline: Array of class IDs (0..4) for baseline year (e.g. 2020).
        grid_comparison: Array of class IDs (0..4) for comparison year (e.g. 2025).
        conf_baseline: Optional per-cell classification confidence values for baseline.
        conf_comparison: Optional per-cell classification confidence values for comparison.
        cell_area_ha: Ground area per cell in hectares (default 0.04 ha = 20m x 20m).
        confidence_threshold: Minimum confidence proxy threshold to flag high-uncertainty change.

    Returns:
        Structured dictionary containing transition matrix, mangrove gain/loss breakdowns,
        net change, confidence summaries, and percentage statistics.
    """
    n_baseline = len(grid_baseline)
    n_comparison = len(grid_comparison)

    if n_baseline == 0 or n_comparison == 0:
        raise ValueError("Cannot compute change detection on empty classification grids.")

    if n_baseline != n_comparison:
        raise SpatialCoverageMismatchError(
            f"Spatial coverage mismatch: baseline grid has {n_baseline} cells, "
            f"while comparison grid has {n_comparison} cells."
        )

    arr_base = np.array(grid_baseline, dtype=int)
    arr_comp = np.array(grid_comparison, dtype=int)

    # Validate class bounds
    for cid in arr_base:
        validate_class_id(cid)
    for cid in arr_comp:
        validate_class_id(cid)

    # Confidences
    if conf_baseline is not None and len(conf_baseline) == n_baseline:
        c_base = np.array(conf_baseline, dtype=float)
    else:
        c_base = np.ones(n_baseline, dtype=float) * 0.90

    if conf_comparison is not None and len(conf_comparison) == n_comparison:
        c_comp = np.array(conf_comparison, dtype=float)
    else:
        c_comp = np.ones(n_comparison, dtype=float) * 0.90

    # Conservative change confidence proxy: min(conf_base, conf_comp)
    c_change = np.minimum(c_base, c_comp)

    total_cells = n_baseline
    total_area_ha = round(total_cells * cell_area_ha, 2)

    # Initialize 5x5 count matrix
    matrix_counts = np.zeros((5, 5), dtype=int)
    for i in range(5):
        for j in range(5):
            mask = (arr_base == i) & (arr_comp == j)
            matrix_counts[i, j] = int(np.sum(mask))

    matrix_areas_ha = np.round(matrix_counts * cell_area_ha, 2).tolist()

    # Detailed list of all 25 transitions
    transitions_list: List[Dict[str, Any]] = []
    for i in range(5):
        source_class_name = get_class_name(i)
        source_total_cells = int(np.sum(matrix_counts[i, :]))

        for j in range(5):
            dest_class_name = get_class_name(j)
            count = int(matrix_counts[i, j])
            area_ha = round(count * cell_area_ha, 2)

            pct_source = (
                round((count / source_total_cells) * 100.0, 2)
                if source_total_cells > 0
                else 0.0
            )
            pct_aoi = round((count / total_cells) * 100.0, 2) if total_cells > 0 else 0.0

            trans_str = f"{source_class_name} -> {dest_class_name}"
            category = categorize_transition(i, j, confidence=1.0)

            transitions_list.append({
                "fromClassId": i,
                "fromClassName": source_class_name,
                "toClassId": j,
                "toClassName": dest_class_name,
                "transition": trans_str,
                "cellCount": count,
                "areaHa": area_ha,
                "percentageOfSource": pct_source,
                "percentageOfAoi": pct_aoi,
                "changeCategory": category,
            })

    # Mangrove class specific analytics (Class ID 0)
    # 2020 Mangrove cells = row 0 sum
    mangrove_2020_cells = int(np.sum(matrix_counts[0, :]))
    mangrove_2020_ha = round(mangrove_2020_cells * cell_area_ha, 2)

    # 2025 Mangrove cells = col 0 sum
    mangrove_2025_cells = int(np.sum(matrix_counts[:, 0]))
    mangrove_2025_ha = round(mangrove_2025_cells * cell_area_ha, 2)

    # Stable mangrove = matrix[0, 0]
    stable_mangrove_cells = int(matrix_counts[0, 0])
    stable_mangrove_ha = round(stable_mangrove_cells * cell_area_ha, 2)

    # Mangrove loss: from=0 to!=0 (Row 0, columns 1..4)
    loss_to_water_ha = round(int(matrix_counts[0, 1]) * cell_area_ha, 2)
    loss_to_aqua_ha = round(int(matrix_counts[0, 2]) * cell_area_ha, 2)
    loss_to_bare_ha = round(int(matrix_counts[0, 3]) * cell_area_ha, 2)
    loss_to_other_ha = round(int(matrix_counts[0, 4]) * cell_area_ha, 2)
    total_loss_ha = round(loss_to_water_ha + loss_to_aqua_ha + loss_to_bare_ha + loss_to_other_ha, 2)

    # Mangrove gain: from!=0 to=0 (Column 0, rows 1..4)
    gain_from_water_ha = round(int(matrix_counts[1, 0]) * cell_area_ha, 2)
    gain_from_aqua_ha = round(int(matrix_counts[2, 0]) * cell_area_ha, 2)
    gain_from_bare_ha = round(int(matrix_counts[3, 0]) * cell_area_ha, 2)
    gain_from_other_ha = round(int(matrix_counts[4, 0]) * cell_area_ha, 2)
    total_gain_ha = round(gain_from_water_ha + gain_from_aqua_ha + gain_from_bare_ha + gain_from_other_ha, 2)

    # Net mangrove change
    net_change_ha = round(total_gain_ha - total_loss_ha, 2)

    # Percentage change with zero-denominator safety
    if mangrove_2020_ha > 0:
        percent_change = round(((mangrove_2025_ha - mangrove_2020_ha) / mangrove_2020_ha) * 100.0, 2)
    else:
        percent_change = None

    # Stable areas per class
    stable_areas_ha: Dict[str, float] = {}
    for i in range(5):
        cname = get_class_name(i)
        stable_areas_ha[cname] = round(int(matrix_counts[i, i]) * cell_area_ha, 2)

    # Confidence analytics
    is_change_mask = (arr_base != arr_comp)
    low_conf_change_mask = is_change_mask & (c_change < confidence_threshold)
    low_conf_cells = int(np.sum(low_conf_change_mask))
    low_conf_area_ha = round(low_conf_cells * cell_area_ha, 2)

    mean_conf_base = round(float(np.mean(c_base)), 4)
    mean_conf_comp = round(float(np.mean(c_comp)), 4)
    mean_conf_change = round(float(np.mean(c_change)), 4)

    return {
        "totalCells": total_cells,
        "totalAreaHa": total_area_ha,
        "cellAreaHa": cell_area_ha,
        "cellSizeMeters": CELL_SIZE_METERS,
        "matrixCounts": matrix_counts.tolist(),
        "matrixAreasHa": matrix_areas_ha,
        "classes": CLASS_NAMES,
        "transitions": transitions_list,
        "stableAreasHa": stable_areas_ha,
        "mangroveSummary": {
            "baselineYear": 2020,
            "comparisonYear": 2025,
            "baselineMangroveHa": mangrove_2020_ha,
            "comparisonMangroveHa": mangrove_2025_ha,
            "grossGainHa": total_gain_ha,
            "grossLossHa": total_loss_ha,
            "netChangeHa": net_change_ha,
            "percentChange": percent_change,
            "stableMangroveHa": stable_mangrove_ha,
            "lossBreakdown": {
                "toWaterHa": loss_to_water_ha,
                "toAquacultureHa": loss_to_aqua_ha,
                "toBareLandHa": loss_to_bare_ha,
                "toOtherVegHa": loss_to_other_ha,
                "totalLossHa": total_loss_ha,
            },
            "gainBreakdown": {
                "fromWaterHa": gain_from_water_ha,
                "fromAquacultureHa": gain_from_aqua_ha,
                "fromBareLandHa": gain_from_bare_ha,
                "fromOtherVegHa": gain_from_other_ha,
                "totalGainHa": total_gain_ha,
            },
        },
        "confidenceSummary": {
            "meanConfidence2020": mean_conf_base,
            "meanConfidence2025": mean_conf_comp,
            "meanChangeConfidence": mean_conf_change,
            "confidenceThreshold": confidence_threshold,
            "lowConfidenceChangeCells": low_conf_cells,
            "lowConfidenceChangeAreaHa": low_conf_area_ha,
            "confidenceScore": round(mean_conf_change * 100.0, 1),
        },
    }
